<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create blog tables for PostgreSQL';
    }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE categories (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORIES_SLUG ON categories (slug)');
        $this->addSql('CREATE TABLE articles (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, image VARCHAR(255) NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(220) NOT NULL, description TEXT NOT NULL, content TEXT NOT NULL, views_count INTEGER DEFAULT 0 NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ARTICLES_SLUG ON articles (slug)');
        $this->addSql('CREATE INDEX ARTICLES_PUBLISHED_AT_IDX ON articles (published_at)');
        $this->addSql('CREATE INDEX ARTICLES_VIEWS_COUNT_IDX ON articles (views_count)');
        $this->addSql('CREATE TABLE article_category (article_id INTEGER NOT NULL, category_id INTEGER NOT NULL, PRIMARY KEY(article_id, category_id))');
        $this->addSql('CREATE INDEX IDX_ARTICLE_CATEGORY_ARTICLE ON article_category (article_id)');
        $this->addSql('CREATE INDEX IDX_ARTICLE_CATEGORY_CATEGORY ON article_category (category_id)');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_ARTICLE_CATEGORY_ARTICLE FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_ARTICLE_CATEGORY_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE article_category');
        $this->addSql('DROP TABLE articles');
        $this->addSql('DROP TABLE categories');
    }
}
